### ISSUE TITLE
Letterboxing/Overlay after Playback

### ISSUE THREAD

**Issue by cyanidecupcake** [notklaatu/stopgo#15] opened 2016-06-01 06:48 UTC
After playing animation, sometimes there will be a letterboxing effect where you see a previous frame with the live feed letterboxed over top of it.  

Playback itself nearly always letterboxes and users complain of not being able to see their complete frame.

![img_20160601_170433_1](https://cloud.githubusercontent.com/assets/13429860/15700668/69412646-2829-11e6-80ad-57e7a0f8d6ca.jpg)

**Comment by notklaatu** [comment] 2016-07-23 09:49
I think I've identified why this happens. in the OnTimer function, I hard coded the resolution of playback (no good reason to do that; it was early in development and I wasn't sure how I was handling resolution yet). I marked the line (814 in gui.py as of this note) with BUGBUG, so I'll take a look at the overall resolution scheme and this should get fixed along with that.

**Comment by notklaatu** [comment] 2016-07-24 10:49
I changed hardcoded res to self.screenWidth, so in theory this should fix the glitch.
Since I can't reproduce the glitch, I'll have to wait til it's tested by 8 year olds. For now, closing

f112c47 selected icons, new styled buttons, possible letterboxglitch fix

**Closed as completed by notklaatu** 2016-07-24 10:49 UTC
Labels: bug, in progress
